set -g pane-border-status bottom
set -g pane-border-format "#[fg=black,bg=blue] #P #{pane_title}"

bind-key 2 split-window -v -p 25% \; select-pane -U
bind u display-popup -E -w 80% -h 80% "motmux --picker"
